BanditProc = BanditProc or {}

function BanditProc.Toilet (sx, sy, sz)
	BanditBasePlacements.IsoObject ("floors_interior_tilesandwood_01_41", sx + 1, sy + 1, sz + 0)
	BanditBasePlacements.IsoThumpable ("walls_exterior_wooden_01_30", sx + 1, sy + 1, sz + 0)
	BanditBasePlacements.IsoObject ("fixtures_bathroom_02_25", sx + 1, sy + 1, sz + 0)
	BanditBasePlacements.IsoObject ("floors_interior_tilesandwood_01_41", sx + 1, sy + 2, sz + 0)
	BanditBasePlacements.IsoThumpable ("walls_exterior_wooden_01_28", sx + 1, sy + 2, sz + 0)
	BanditBasePlacements.IsoThumpable ("walls_exterior_wooden_01_39", sx + 1, sy + 3, sz + 0)
	BanditBasePlacements.IsoObject ("fixtures_doors_frames_01_9", sx + 1, sy + 3, sz + 0)
	BanditBasePlacements.IsoDoor ("fixtures_bathroom_02_33", sx + 1, sy + 3, sz + 0)
	BanditBasePlacements.IsoObject ("floors_interior_tilesandwood_01_41", sx + 2, sy + 1, sz + 0)
	BanditBasePlacements.IsoThumpable ("walls_exterior_wooden_01_29", sx + 2, sy + 1, sz + 0)
	BanditBasePlacements.IsoObject ("floors_interior_tilesandwood_01_41", sx + 2, sy + 2, sz + 0)
	BanditBasePlacements.IsoThumpable ("walls_exterior_wooden_01_29", sx + 2, sy + 3, sz + 0)
	BanditBasePlacements.IsoThumpable ("walls_exterior_wooden_01_28", sx + 3, sy + 1, sz + 0)
	BanditBasePlacements.IsoObject ("roofs_01_39", sx + 3, sy + 1, sz + 0)
	BanditBasePlacements.IsoThumpable ("walls_exterior_wooden_01_28", sx + 3, sy + 2, sz + 0)
	BanditBasePlacements.IsoObject ("roofs_01_39", sx + 3, sy + 2, sz + 0)
	BanditBasePlacements.IsoObject ("walls_exterior_wooden_01_31", sx + 3, sy + 3, sz + 0)
	BanditBasePlacements.IsoThumpable ("walls_exterior_roofs_06_37", sx + 1, sy + 3, sz + 1)
	BanditBasePlacements.IsoObject ("roofs_01_37", sx + 2, sy + 1, sz + 1)
	BanditBasePlacements.IsoObject ("roofs_01_37", sx + 2, sy + 2, sz + 1)
	BanditBasePlacements.IsoThumpable ("walls_exterior_roofs_06_29", sx + 2, sy + 3, sz + 1)

    BanditBasePlacements.IsoObject ("carpentry_02_56", sx + 1, sy + 1, sz + 1)
	BanditBasePlacements.IsoObject ("carpentry_02_56", sx + 2, sy + 1, sz + 1)
	BanditBasePlacements.IsoObject ("carpentry_02_56", sx + 1, sy + 2, sz + 1)
	BanditBasePlacements.IsoObject ("carpentry_02_56", sx + 2, sy + 2, sz + 1)
end